<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property enum $status
 * @property string $activate_code
 * @property integer $activated
 * @property string $profile_image
 * @property integer $score
 * @property integer $login_count
 * @property sfGuardUser $User
 * 
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method string      getFirstName()        Returns the current record's "first_name" value
 * @method string      getLastName()         Returns the current record's "last_name" value
 * @method string      getEmail()            Returns the current record's "email" value
 * @method enum        getStatus()           Returns the current record's "status" value
 * @method string      getActivateCode()     Returns the current record's "activate_code" value
 * @method integer     getActivated()        Returns the current record's "activated" value
 * @method string      getProfileImage()     Returns the current record's "profile_image" value
 * @method integer     getScore()            Returns the current record's "score" value
 * @method integer     getLoginCount()       Returns the current record's "login_count" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method Profile     setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Profile     setFirstName()        Sets the current record's "first_name" value
 * @method Profile     setLastName()         Sets the current record's "last_name" value
 * @method Profile     setEmail()            Sets the current record's "email" value
 * @method Profile     setStatus()           Sets the current record's "status" value
 * @method Profile     setActivateCode()     Sets the current record's "activate_code" value
 * @method Profile     setActivated()        Sets the current record's "activated" value
 * @method Profile     setProfileImage()     Sets the current record's "profile_image" value
 * @method Profile     setScore()            Sets the current record's "score" value
 * @method Profile     setLoginCount()       Sets the current record's "login_count" value
 * @method Profile     setUser()             Sets the current record's "User" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('sf_guard_user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'email' => true,
             'length' => '255',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'active',
              1 => 'pending',
              2 => 'flagged',
              3 => 'disabled',
             ),
             'default' => 'pending',
             ));
        $this->hasColumn('activate_code', 'string', 14, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '14',
             ));
        $this->hasColumn('activated', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('profile_image', 'string', 50, array(
             'type' => 'string',
             'default' => 'user_profile_default.png',
             'length' => '50',
             ));
        $this->hasColumn('score', 'integer', 11, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '11',
             ));
        $this->hasColumn('login_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}