Profile:
  columns:
    sf_guard_user_id: integer(11)
    first_name:
      type: string(255)
    last_name:
      type: string(255)
    email:
      type: string(255)
      notnull: true
      email: true
    status:
      type: enum
      values: [active, pending, flagged, disabled]
      default: pending
    activate_code:
      type: string(14)
      notnull: true
    activated:
      type: integer(1)
      default: 0
    profile_image:
      type: string(50)
      default: user_profile_default.png
    score:
      type: integer(11)
      default: 0
    login_count:
      type: integer
      default: 0
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Profile
      foreignType: one
      onDelete: CASCADE